[package]
name = "fabric-endpoint-mdm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fabric-types = { path = "../../core/types" }
plist.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
